"""empty message

Revision ID: 951031be6257
Revises: 7be3c97f54f6
Create Date: 2018-06-09 21:08:33.155467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951031be6257'
down_revision = '7be3c97f54f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucketlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bucketlists')
    # ### end Alembic commands ###
